### ISSUE TITLE
Use single quotes for pact term creation error message to avoid \" in message

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-support#46]
`Value to generate \"/api/check-bsb/999-999\" does not match regular expression /\\/api\\/check-bsb\\/d{3}-d{3}/"`

The \" doesn't look good.

**Comment by bheemreddy181** [comment]
Seeing a similar issue by any chance do you know what we are doing wrong 

```
	 4: from /home/circleci/project/vendor/bundle/ruby/2.5.0/gems/pact-support-1.16.8/lib/pact/matching_rules/merge.rb:41:in `recurse'
	 3: from /home/circleci/project/vendor/bundle/ruby/2.5.0/gems/pact-support-1.16.8/lib/pact/matching_rules/merge.rb:85:in `wrap'
	 2: from /home/circleci/project/vendor/bundle/ruby/2.5.0/gems/pact-support-1.16.8/lib/pact/matching_rules/merge.rb:100:in `handle_regex'
	 1: from /home/circleci/project/vendor/bundle/ruby/2.5.0/gems/pact-support-1.16.8/lib/pact/matching_rules/merge.rb:100:in `new'
/home/circleci/project/vendor/bundle/ruby/2.5.0/gems/pact-support-1.16.8/lib/pact/term.rb:31:in `initialize': Value to generate "{"case_types"=>["Bankruptcy", "Credit counseling", "Legal complaint", "ID theft", "Contingent Placement", "Deceased", "Cease & Desist", "Credit Reporting", "Debt Sale"], "loan_number"=>"2021IL316410875"}" does not match regular expression /\S.*loan_number=\d{4}[A-Z]{2}\d*/ (Pact::Error)
```

**Comment by bethesque** [comment]
The thing it's being asked to generate is a hash. You can't match a hash against a regular expression.

**Comment by bheemreddy181** [comment]
Well this was working in the older version of pact support gem - surprisingly 
![Uploading Screen Shot 2021-07-27 at 4.56.30 PM.png…]()

**Comment by bethesque** [comment]
There's no change that I can think of immediately that would have affected that. Please create a reproducible example using https://github.com/pact-foundation/pact-ruby-e2e-example

**Comment by bethesque** [comment]
Btw, 1.32.0 is VERY old! It's from 2018-07-25.
